version: '3.9'

services:
  users-service:
    build: ./users-service
    ports:
      - "3000:3000"

  orders-service:
    build: ./orders-service
    ports:
      - "3001:3001"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3002:3002"
    environment:
      - USERS_SERVICE_URL=http://users-service:3000
      - ORDERS_SERVICE_URL=http://orders-service:3001
    depends_on:
      - users-service
      - orders-service